"""Run every report's reproduce.py and write reports/REPRODUCTION_SUMMARY.md.

Run from the repository root:
    python reports/run_all.py                 # every report
    python reports/run_all.py WRP_2021        # only folders whose path contains WRP_2021

Run reports/run_all.R first if you want the R column filled in as well.
Exits non-zero if any script hits a code error (not for figures that
differ from the published ones -- those are listed in the summary).
"""

import subprocess
import sys
from pathlib import Path

REPORTS = Path(__file__).resolve().parent
sys.path.insert(0, str(REPORTS))

from wrp import STATUS_ORDER, build_table  # noqa: E402


def report_dirs(pattern=""):
    return sorted(
        p.parent for p in REPORTS.glob("WRP_*/*/reproduce.py") if pattern in str(p.parent)
    )


def main():
    pattern = sys.argv[1] if len(sys.argv) > 1 else ""
    dirs = report_dirs(pattern)
    failed = []
    for d in dirs:
        print(f"\n== {d.relative_to(REPORTS)}")
        if subprocess.run([sys.executable, str(d / "reproduce.py")], cwd=REPORTS.parent).returncode:
            failed.append(d)

    lines = [
        "# Reproduction summary",
        "",
        "Generated by `reports/run_all.py`. One row per report; follow the link for every "
        "finding, its published value, the Python and R results and notes.",
        "",
        "| Wave | Report | " + " | ".join(STATUS_ORDER) + " | Total |",
        "| --- | --- | " + " | ".join("---" for _ in STATUS_ORDER) + " | --- |",
    ]
    totals = dict.fromkeys(STATUS_ORDER, 0)
    for d in dirs:
        counts = build_table(d)["status"].value_counts()
        cells = [str(counts.get(s, 0)) for s in STATUS_ORDER]
        link = f"[{d.name}]({d.relative_to(REPORTS).as_posix()}/RESULTS.md)"
        lines.append(f"| {d.parent.name} | {link} | " + " | ".join(cells) + f" | {counts.sum()} |")
        for s in STATUS_ORDER:
            totals[s] += int(counts.get(s, 0))
    lines.append("| **All** | **{} reports** | ".format(len(dirs))
                 + " | ".join(f"**{totals[s]}**" for s in STATUS_ORDER) + f" | **{sum(totals.values())}** |")
    if not pattern:
        (REPORTS / "REPRODUCTION_SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("\nWrote reports/REPRODUCTION_SUMMARY.md")

    if failed:
        print("\nScripts with code errors:", *[str(d.relative_to(REPORTS)) for d in failed], sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
